name: Code Quality Checks

on: [ push ]

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Auto-fix with Ruff
        run: ruff check . --fix

      - name: Format with Black
        run: black .

      - name: Auto-commit fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-fix with Ruff & Black"
          git push
